;this file for FamiTone2 library generated by text2data tool

kk_main_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env3
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$ce,$cd,$cc,$cb,$05,$ca,$05,$c9,$08,$c8,$0b,$c8,$00,$0c
@env2:
	.byte $cf,$ce,$cd,$c0,$00,$03
@env3:
	.byte $c0,$0e,$c3,$c3,$c0,$bd,$bd,$c0,$00,$02


@song0ch0:
@ref0:
	.byte $80,$1a,$00,$1b,$33,$1a,$81
@ref1:
	.byte $15,$01,$11,$00,$81
@ref2:
	.byte $87,$11,$00,$81
@ref3:
	.byte $14,$8d
@song0ch0loop:
@ref4:
	.byte $80,$1b,$01,$29,$1b,$11,$01,$15,$01,$1b,$01,$29,$1b,$11,$01,$15
	.byte $00,$81
@ref5:
	.byte $1b,$01,$29,$1b,$11,$01,$15,$01,$1b,$01,$29,$1b,$11,$01,$1b,$00
	.byte $81
@ref6:
	.byte $15,$01,$23,$15,$0b,$01,$11,$01,$15,$01,$23,$15,$0b,$01,$11,$00
	.byte $81
	.byte $ff,$11
	.word @ref6
@ref8:
	.byte $1b,$01,$29,$1b,$11,$01,$15,$01,$1b,$01,$29,$1b,$11,$01,$15,$00
	.byte $81
	.byte $ff,$11
	.word @ref5
	.byte $ff,$11
	.word @ref6
	.byte $ff,$11
	.word @ref6
@ref12:
	.byte $25,$01,$33,$25,$1b,$01,$1f,$01,$25,$01,$33,$25,$1b,$01,$1f,$00
	.byte $81
@ref13:
	.byte $25,$01,$33,$25,$1b,$01,$1f,$01,$25,$01,$33,$25,$1b,$01,$25,$00
	.byte $81
	.byte $ff,$11
	.word @ref8
	.byte $ff,$11
	.word @ref5
	.byte $ff,$11
	.word @ref12
	.byte $ff,$11
	.word @ref13
	.byte $ff,$11
	.word @ref8
	.byte $ff,$11
	.word @ref5
@ref20:
	.byte $25,$01,$33,$25,$1b,$01,$33,$01,$25,$01,$33,$25,$1b,$01,$33,$00
	.byte $81
@ref21:
	.byte $1b,$01,$29,$1b,$11,$01,$29,$01,$1b,$01,$29,$1b,$11,$01,$29,$00
	.byte $81
	.byte $ff,$11
	.word @ref20
	.byte $ff,$11
	.word @ref21
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref24:
	.byte $80,$58,$00,$58,$00,$01,$58,$00
@ref25:
	.byte $52,$00,$83,$4f,$00,$81
@ref26:
	.byte $87,$4f,$00,$00
@ref27:
	.byte $52,$8b,$00
@song0ch1loop:
@ref28:
	.byte $80,$4a,$8d,$00,$85,$52,$83,$00,$4a,$89,$01,$4a,$83,$00,$52,$83
	.byte $00
@ref29:
	.byte $52,$83,$00,$58,$00,$52,$00,$52,$83,$00,$52,$83,$00,$4a,$83,$00
	.byte $52,$00,$4a,$00,$3a,$83,$00,$44,$83,$00
@ref30:
	.byte $3a,$8d,$00,$85,$44,$00,$83,$3a,$85,$3b,$3b,$45,$01,$45,$00,$81
@ref31:
	.byte $3a,$01,$00,$3a,$00,$3b,$44,$00,$83,$3a,$00,$45,$44,$01,$00,$4b
	.byte $01,$53,$01,$4b,$00,$81
@ref32:
	.byte $4a,$8d,$00,$85,$52,$83,$00,$4a,$89,$01,$4a,$83,$00,$52,$83,$00
	.byte $ff,$1a
	.word @ref29
	.byte $ff,$10
	.word @ref30
	.byte $ff,$16
	.word @ref31
@ref36:
	.byte $4a,$8d,$4a,$85,$44,$85,$4a,$8d,$4e,$8d
@ref37:
	.byte $4a,$8d,$44,$85,$44,$85,$4e,$85,$4a,$85,$3a,$85,$3a,$85
@ref38:
	.byte $40,$8d,$41,$45,$40,$85,$41,$45,$40,$85,$3a,$85,$28,$85
@ref39:
	.byte $3a,$9d,$00,$9d
	.byte $ff,$0a
	.word @ref36
	.byte $ff,$0e
	.word @ref37
	.byte $ff,$0e
	.word @ref38
@ref43:
	.byte $3a,$9d,$00,$9d
@ref44:
	.byte $3c,$85,$3d,$33,$3c,$85,$44,$85,$44,$8d,$44,$85,$44,$85
@ref45:
	.byte $3a,$85,$3b,$3b,$3a,$85,$28,$85,$32,$9d
@ref46:
	.byte $3c,$85,$3d,$33,$3c,$85,$44,$85,$44,$85,$44,$85,$3c,$85,$2c,$85
@ref47:
	.byte $3b,$3b,$3a,$85,$32,$85,$28,$85,$32,$9d
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref48:
	.byte $80,$7a,$00,$7a,$00,$01,$7a,$00
@ref49:
	.byte $74,$00,$83,$70,$00,$83
@ref50:
	.byte $87,$70,$01,$00
@ref51:
	.byte $74,$8b,$00
@song0ch2loop:
@ref52:
	.byte $80,$6a,$8d,$00,$85,$70,$83,$00,$6a,$89,$01,$6a,$83,$00,$70,$83
	.byte $00
@ref53:
	.byte $74,$83,$00,$7a,$00,$74,$00,$70,$83,$00,$74,$83,$00,$6a,$83,$00
	.byte $70,$00,$6a,$00,$66,$83,$00,$62,$83,$00
@ref54:
	.byte $5c,$8d,$00,$85,$62,$00,$83,$5c,$85,$59,$5d,$63,$01,$67,$00,$81
@ref55:
	.byte $5c,$01,$00,$58,$00,$5d,$62,$00,$83,$5c,$00,$63,$66,$01,$00,$6b
	.byte $01,$71,$01,$6b,$00,$81
@ref56:
	.byte $6a,$8d,$00,$85,$70,$83,$00,$6a,$89,$01,$6a,$83,$00,$70,$83,$00
	.byte $ff,$1a
	.word @ref53
	.byte $ff,$10
	.word @ref54
	.byte $ff,$16
	.word @ref55
@ref60:
	.byte $54,$89,$01,$54,$83,$00,$32,$83,$00,$54,$8d,$00,$8d
@ref61:
	.byte $54,$8b,$00,$54,$83,$00,$62,$83,$00,$5c,$83,$00,$5c,$83,$00,$5c
	.byte $83,$00,$4a,$83,$00
@ref62:
	.byte $52,$8d,$52,$00,$52,$00,$52,$83,$00,$52,$00,$52,$00,$52,$83,$00
	.byte $4a,$83,$00,$3a,$83,$00
@ref63:
	.byte $40,$9d,$00,$9d
	.byte $ff,$0d
	.word @ref60
	.byte $ff,$15
	.word @ref61
	.byte $ff,$16
	.word @ref62
@ref67:
	.byte $40,$9d,$00,$9d
@ref68:
	.byte $5c,$85,$5d,$55,$5c,$85,$66,$85,$62,$8d,$66,$85,$62,$85
@ref69:
	.byte $58,$85,$59,$5d,$58,$85,$4a,$85,$52,$9d
@ref70:
	.byte $5c,$85,$5d,$55,$5c,$85,$62,$85,$66,$85,$62,$85,$5c,$85,$62,$85
@ref71:
	.byte $59,$5d,$58,$85,$52,$85,$4a,$85,$52,$99,$00,$81
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref72:
	.byte $82,$03,$02,$85,$02,$81
@ref73:
	.byte $06,$85,$02,$85
@ref74:
	.byte $87,$02,$85
@ref75:
	.byte $06,$8d
@song0ch3loop:
@ref76:
	.byte $82,$04,$85,$03,$03,$06,$85,$02,$85,$04,$85,$03,$03,$06,$85,$02
	.byte $85
@ref77:
	.byte $04,$85,$03,$03,$06,$85,$02,$85,$04,$85,$03,$03,$06,$85,$02,$85
	.byte $ff,$10
	.word @ref77
@ref79:
	.byte $04,$85,$03,$03,$06,$85,$02,$85,$04,$85,$07,$07,$06,$85,$06,$85
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref79
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref79
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref79
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref77
	.byte $ff,$10
	.word @ref79
	.byte $fd
	.word @song0ch3loop

@song0ch4:
	.byte $fb,$03
@ref96:
	.byte $fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb
	.byte $04,$81,$fb,$03,$81,$fb,$04,$81
	.byte $ff,$08
	.word @ref96
	.byte $ff,$08
	.word @ref96
	.byte $ff,$08
	.word @ref96
@song0ch4loop:
@ref100:
	.byte $fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb
	.byte $04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03
	.byte $81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81
	.byte $fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb
	.byte $04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03
	.byte $81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81,$fb,$03,$81,$fb,$04,$81
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $ff,$20
	.word @ref100
	.byte $fd
	.word @song0ch4loop
